[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/02_softmax.ipynb)

# 🟢 Easy: Implement Softmax

Implement the **Softmax** function from scratch.

$$\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$$

### Signature
```python
def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `torch.softmax`, `F.softmax`, or `torch.nn.Softmax`
- Must be **numerically stable** (hint: subtract `max` before `exp`)

### Example
```
Input:  tensor([1., 2., 3.])
Output: tensor([0.0900, 0.2447, 0.6652])  # sums to 1.0
```

In [1]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 3.1 MB/s eta 0:00:00


In [2]:
import torch

In [11]:
# ✏️ YOUR IMPLEMENTATION HERE

def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    exp_values = torch.exp(x)
    # print(exp_values)
    # print(exp_values.sum(dim=dim, keepdim=True))
    return exp_values / exp_values.sum(dim=dim, keepdim=True)

In [12]:
# 🧪 Debug
x = torch.tensor([1.0, 2.0, 3.0])
print("Output:", my_softmax(x, dim=-1))
print("Sum:   ", my_softmax(x, dim=-1).sum())  # should be ~1.0
print("Ref:   ", torch.softmax(x, dim=-1))

tensor([ 2.7183,  7.3891, 20.0855])
tensor([30.1929])
Output: tensor([0.0900, 0.2447, 0.6652])
tensor([ 2.7183,  7.3891, 20.0855])
tensor([30.1929])
Sum:    tensor(1.)
Ref:    tensor([0.0900, 0.2447, 0.6652])


In [5]:
# ✅ SUBMIT
from torch_judge import check
check("softmax")


🧪 Testing: Implement Softmax (Easy)
──────────────────────────────────────────────────
  ❌ [1/3] Basic 1-D
     tensor([0.4530, 1.2315, 3.3476]) vs tensor([0.0900, 0.2447, 0.6652])
  💥 [2/3] 2-D along dim=-1
     RuntimeError: The size of tensor a (8) must match the size of tensor b (4) at non-singleton dimension 1
         return exp_values / x.sum(dim=dim)
           ~~~~~~~~~~~^~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (8) must match the size of tensor b (4) at non-singleton dimension 1
  ❌ [3/3] Numerical stability
     Inf in output — not numerically stable
──────────────────────────────────────────────────
  📊 0/3 tests passed.
  Keep going! Use hint("softmax") if you're stuck.

